import {
  StudentProfile,
  AdminUser,
  TemplateConfig,
  MedicalLeaveApplication,
} from "../types";

// Default University Template
export const defaultTemplate: TemplateConfig = {
  id: "DAVU-TMPL-2026",
  universityName: "DAV UNIVERSITY",
  universitySub: "JALANDHAR, PUNJAB (Established under Punjab Act No. 8 of 2013)",
  recipient: "The Dean of Academic Affairs / Head of Department\nDAV University\nNH-44, Sarmastpur, Jalandhar – 144012, Punjab",
  subject: "Application for Medical Leave — {{application_id}}",
  salutation: "Respected Sir / Madam,",
  body: `I, {{student_name}}, bearing Student ID {{student_id}}, a regular student of {{program}}, {{department}}, {{semester}}, Section {{section}}, request medical leave from {{start_date}} to {{end_date}} (total {{number_of_days}} day(s)) due to {{medical_reason}}.

I was under medical consultation and treatment advised by {{doctor_name}} on {{consultation_date}}. The official medical certificate and prescription documents have been submitted for verification.

I kindly request you to grant me medical leave for the above-mentioned period and condone my absence in academic records as per DAV University attendance regulations.`,
  signoff: "Thanking you.\n\nYours sincerely,",
  footerNotes: "Note: This is a system-generated official medical leave application submitted through DAV University Medical Leave Application Portal. Verification ID: {{application_id}}",
  updatedAt: new Date().toISOString(),
};

// Seed Students
export const initialStudents: StudentProfile[] = [
  {
    id: "std-001",
    studentId: "DAVU/2023/CSE/1042",
    name: "Rahul Verma",
    email: "rahul.verma@davuniversity.org",
    phone: "+91 98765 43210",
    program: "B.Tech Computer Science & Engineering",
    department: "Department of Computer Science & Engineering",
    semester: "5th Semester",
    section: "CSE-A",
    academicSession: "2026-2027",
    parentName: "Sh. Rakesh Verma",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    createdAt: "2023-08-01T09:00:00.000Z",
  },
  {
    id: "std-002",
    studentId: "DAVU/2024/BIO/2015",
    name: "Priya Sharma",
    email: "priya.sharma@davuniversity.org",
    phone: "+91 98123 45678",
    program: "B.Sc Biotechnology (Hons.)",
    department: "Department of Biotechnology",
    semester: "3rd Semester",
    section: "BIO-1",
    academicSession: "2026-2027",
    parentName: "Sh. Anand Sharma",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    createdAt: "2024-08-01T09:00:00.000Z",
  },
  {
    id: "std-003",
    studentId: "DAVU/2023/MBA/3088",
    name: "Gurpreet Singh",
    email: "gurpreet.singh@davuniversity.org",
    phone: "+91 97800 11223",
    program: "Master of Business Administration (MBA)",
    department: "DAV University Institute of Management",
    semester: "3rd Semester",
    section: "MBA-Finance",
    academicSession: "2026-2027",
    parentName: "S. Balwinder Singh",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    createdAt: "2023-08-01T09:00:00.000Z",
  },
  {
    id: "std-004",
    studentId: "DAVU/2022/PHARM/4102",
    name: "Ananya Gupta",
    email: "ananya.gupta@davuniversity.org",
    phone: "+91 94178 99887",
    program: "Bachelor of Pharmacy (B.Pharm)",
    department: "Department of Pharmaceutical Sciences",
    semester: "7th Semester",
    section: "PHARM-B",
    academicSession: "2026-2027",
    parentName: "Dr. Vinod Gupta",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    createdAt: "2022-08-01T09:00:00.000Z",
  },
];

// Seed Admins
export const initialAdmins: AdminUser[] = [
  {
    id: "adm-001",
    name: "Dr. Rajesh Kumar",
    email: "dean.academics@davuniversity.org",
    role: "Dean of Academic Affairs",
    department: "Office of Academic Affairs",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "adm-002",
    name: "Dr. Meenakshi Sundaram",
    email: "hod.cse@davuniversity.org",
    role: "Head of Department",
    department: "Department of Computer Science & Engineering",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "adm-003",
    name: "Dr. Harshita Batra",
    email: "medical.officer@davuniversity.org",
    role: "University Medical Officer",
    department: "DAV University Health Centre",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80",
  },
];

export const sampleCertDataUri =
  "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='600' height='800' viewBox='0 0 600 800'><rect width='600' height='800' fill='%23fafafa' stroke='%23334155' stroke-width='4'/><rect x='20' y='20' width='560' height='760' fill='%23ffffff' stroke='%230f2b5c' stroke-width='2'/><text x='300' y='70' font-family='Arial' font-size='20' font-weight='bold' fill='%230f2b5c' text-anchor='middle'>CITY MULTISPECIALITY HOSPITAL &amp; CLINIC</text><text x='300' y='95' font-family='Arial' font-size='12' fill='%2364748b' text-anchor='middle'>Model Town, Jalandhar, Punjab - Ph: 0181-2244889</text><line x1='50' y1='115' x2='550' y2='115' stroke='%23ed1c24' stroke-width='2'/><text x='300' y='150' font-family='Arial' font-size='18' font-weight='bold' fill='%23ed1c24' text-anchor='middle'>MEDICAL FITNESS &amp; REST CERTIFICATE</text><text x='60' y='210' font-family='Arial' font-size='14' fill='%231e293b'>This is to certify that the patient was under my medical care and consultation.</text><text x='60' y='250' font-family='Arial' font-size='14' fill='%231e293b'>Diagnosis: Acute Viral Illness / High Grade Pyrexia</text><text x='60' y='290' font-family='Arial' font-size='14' fill='%231e293b'>Advised complete bed rest and clinical observation.</text><text x='60' y='330' font-family='Arial' font-size='14' fill='%231e293b'>Medications prescribed. Patient is recovering and fit to resume studies.</text><circle cx='480' cy='650' r='55' fill='none' stroke='%232563eb' stroke-width='2'/><text x='480' y='645' font-family='Arial' font-size='10' font-weight='bold' fill='%232563eb' text-anchor='middle'>HOSPITAL VERIFIED</text><text x='480' y='665' font-family='Arial' font-size='9' fill='%232563eb' text-anchor='middle'>REG NO: PMC/88341</text><line x1='380' y1='730' x2='540' y2='730' stroke='%230f172a' stroke-width='1.5'/><text x='460' y='748' font-family='Arial' font-size='12' font-weight='bold' fill='%230f172a' text-anchor='middle'>Authorized Medical Officer</text></svg>";

// Seed Applications
export const initialApplications: MedicalLeaveApplication[] = [
  {
    id: "app-101",
    applicationId: "DAV-MED-2026-000101",
    studentDbId: "std-001",
    studentId: "DAVU/2023/CSE/1042",
    studentName: "Rahul Verma",
    email: "rahul.verma@davuniversity.org",
    phone: "+91 98765 43210",
    program: "B.Tech Computer Science & Engineering",
    department: "Department of Computer Science & Engineering",
    semester: "5th Semester",
    section: "CSE-A",
    academicSession: "2026-2027",
    parentName: "Sh. Rakesh Verma",
    leaveType: "Medical Leave",
    startDate: "2026-09-18",
    endDate: "2026-09-22",
    numberOfDays: 5,
    reason: "Acute Viral Pyrexia with severe body aches and dehydration",
    applicationDate: "2026-09-23",
    doctorName: "Dr. A. K. Joshi, M.D. (Civil Hospital Jalandhar)",
    consultationDate: "2026-09-18",
    treatmentDetails: "Antibiotic regimen, paracetamol, hydration and mandatory 5 days bed rest",
    medicalCertificateName: "Medical_Certificate_RahulVerma.pdf",
    medicalCertificateUrl: sampleCertDataUri,
    medicalCertificateSize: "245 KB",
    declarationAccepted: true,
    status: "Approved",
    adminRemarks: "Verified with Civil Hospital OPD record. Leave granted for 5 days.",
    reviewedBy: "Dr. Rajesh Kumar (Dean of Academic Affairs)",
    reviewedAt: "2026-09-24T14:30:00.000Z",
    submittedAt: "2026-09-23T10:15:00.000Z",
    createdAt: "2026-09-23T10:15:00.000Z",
    updatedAt: "2026-09-24T14:30:00.000Z",
    timeline: [
      {
        id: "t-1",
        status: "Submitted",
        title: "Application Submitted",
        description: "Student submitted medical leave application with attached certificate.",
        timestamp: "2026-09-23T10:15:00.000Z",
        actor: "Rahul Verma (Student)",
      },
      {
        id: "t-2",
        status: "Under Review",
        title: "Document Verification in Progress",
        description: "Application forwarded to University Medical Officer for verification.",
        timestamp: "2026-09-23T14:00:00.000Z",
        actor: "Academic Registrar Office",
      },
      {
        id: "t-3",
        status: "Approved",
        title: "Medical Leave Approved",
        description: "Leave sanctioned for 5 days. Attendance adjustment notice issued.",
        timestamp: "2026-09-24T14:30:00.000Z",
        actor: "Dr. Rajesh Kumar (Dean of Academic Affairs)",
        remarks: "Verified with Civil Hospital OPD record. Leave granted for 5 days.",
      },
    ],
  },
  {
    id: "app-102",
    applicationId: "DAV-MED-2026-000102",
    studentDbId: "std-002",
    studentId: "DAVU/2024/BIO/2015",
    studentName: "Priya Sharma",
    email: "priya.sharma@davuniversity.org",
    phone: "+91 98123 45678",
    program: "B.Sc Biotechnology (Hons.)",
    department: "Department of Biotechnology",
    semester: "3rd Semester",
    section: "BIO-1",
    academicSession: "2026-2027",
    parentName: "Sh. Anand Sharma",
    leaveType: "Medical Leave",
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    numberOfDays: 3,
    reason: "Severe Acute Food Poisoning and Gastrointestinal infection",
    applicationDate: "2026-09-28",
    doctorName: "Dr. Shalini Kapoor, MBBS (Care Clinic Jalandhar)",
    consultationDate: "2026-09-25",
    treatmentDetails: "IV fluid support, antiemetics and oral rehydration salt therapy",
    medicalCertificateName: "Priya_Sharma_CareClinic_Cert.jpg",
    medicalCertificateUrl: sampleCertDataUri,
    medicalCertificateSize: "512 KB",
    declarationAccepted: true,
    status: "Under Review",
    adminRemarks: "Under medical document cross-verification by health desk.",
    reviewedBy: "Dr. Harshita Batra",
    reviewedAt: "2026-09-29T11:00:00.000Z",
    submittedAt: "2026-09-28T09:30:00.000Z",
    createdAt: "2026-09-28T09:30:00.000Z",
    updatedAt: "2026-09-29T11:00:00.000Z",
    timeline: [
      {
        id: "t-1",
        status: "Submitted",
        title: "Application Submitted",
        description: "Medical leave submitted by student.",
        timestamp: "2026-09-28T09:30:00.000Z",
        actor: "Priya Sharma (Student)",
      },
      {
        id: "t-2",
        status: "Under Review",
        title: "Medical Centre Review",
        description: "Under clinical review by University Medical Officer Dr. Harshita Batra.",
        timestamp: "2026-09-29T11:00:00.000Z",
        actor: "Dr. Harshita Batra",
        remarks: "Prescription dates aligned. Finalizing endorsement.",
      },
    ],
  },
  {
    id: "app-103",
    applicationId: "DAV-MED-2026-000103",
    studentDbId: "std-003",
    studentId: "DAVU/2023/MBA/3088",
    studentName: "Gurpreet Singh",
    email: "gurpreet.singh@davuniversity.org",
    phone: "+91 97800 11223",
    program: "Master of Business Administration (MBA)",
    department: "DAV University Institute of Management",
    semester: "3rd Semester",
    section: "MBA-Finance",
    academicSession: "2026-2027",
    parentName: "S. Balwinder Singh",
    leaveType: "Medical Leave",
    startDate: "2026-09-29",
    endDate: "2026-10-03",
    numberOfDays: 5,
    reason: "Right Ankle Grade-2 Ligament Sprain during university sports trial",
    applicationDate: "2026-09-30",
    doctorName: "Dr. Harpreet Chawla, MS Orthopaedics (Ortho Care Jalandhar)",
    consultationDate: "2026-09-29",
    treatmentDetails: "Immobilization splint applied, NSAIDs and strict non-weight bearing advice",
    medicalCertificateName: "Gurpreet_Ortho_Sprain_Cert.pdf",
    medicalCertificateUrl: sampleCertDataUri,
    medicalCertificateSize: "320 KB",
    declarationAccepted: true,
    status: "Submitted",
    adminRemarks: "",
    submittedAt: "2026-09-30T16:45:00.000Z",
    createdAt: "2026-09-30T16:45:00.000Z",
    updatedAt: "2026-09-30T16:45:00.000Z",
    timeline: [
      {
        id: "t-1",
        status: "Submitted",
        title: "Application Submitted",
        description: "Application successfully submitted into university queue.",
        timestamp: "2026-09-30T16:45:00.000Z",
        actor: "Gurpreet Singh (Student)",
      },
    ],
  },
  {
    id: "app-104",
    applicationId: "DAV-MED-2026-000104",
    studentDbId: "std-004",
    studentId: "DAVU/2022/PHARM/4102",
    studentName: "Ananya Gupta",
    email: "ananya.gupta@davuniversity.org",
    phone: "+91 94178 99887",
    program: "Bachelor of Pharmacy (B.Pharm)",
    department: "Department of Pharmaceutical Sciences",
    semester: "7th Semester",
    section: "PHARM-B",
    academicSession: "2026-2027",
    parentName: "Dr. Vinod Gupta",
    leaveType: "Medical Leave",
    startDate: "2026-09-12",
    endDate: "2026-09-19",
    numberOfDays: 8,
    reason: "Enteric Fever (Typhoid) with sustained high temperature",
    applicationDate: "2026-09-20",
    doctorName: "Dr. S. K. Mahajan, MD",
    consultationDate: "2026-09-12",
    treatmentDetails: "Antibiotics, Widal positive test report",
    medicalCertificateName: "Ananya_Typhoid_Cert.pdf",
    medicalCertificateUrl: sampleCertDataUri,
    medicalCertificateSize: "180 KB",
    declarationAccepted: true,
    status: "Returned for Correction",
    adminRemarks: "Widal test lab report is missing. Please re-upload certificate along with clinical lab test report.",
    reviewedBy: "Dr. Harshita Batra (University Medical Officer)",
    reviewedAt: "2026-09-21T15:20:00.000Z",
    submittedAt: "2026-09-20T11:10:00.000Z",
    createdAt: "2026-09-20T11:10:00.000Z",
    updatedAt: "2026-09-21T15:20:00.000Z",
    timeline: [
      {
        id: "t-1",
        status: "Submitted",
        title: "Application Submitted",
        description: "Submitted for review.",
        timestamp: "2026-09-20T11:10:00.000Z",
        actor: "Ananya Gupta (Student)",
      },
      {
        id: "t-2",
        status: "Returned for Correction",
        title: "Correction Requested by Medical Officer",
        description: "Widal test lab report is missing. Please re-upload certificate along with clinical lab test report.",
        timestamp: "2026-09-21T15:20:00.000Z",
        actor: "Dr. Harshita Batra",
        remarks: "Widal test lab report is missing. Please re-upload certificate along with clinical lab test report.",
      },
    ],
  },
  {
    id: "app-105",
    applicationId: "DAV-MED-2026-000098",
    studentDbId: "std-001",
    studentId: "DAVU/2023/CSE/1042",
    studentName: "Rahul Verma",
    email: "rahul.verma@davuniversity.org",
    phone: "+91 98765 43210",
    program: "B.Tech Computer Science & Engineering",
    department: "Department of Computer Science & Engineering",
    semester: "5th Semester",
    section: "CSE-A",
    academicSession: "2026-2027",
    parentName: "Sh. Rakesh Verma",
    leaveType: "Medical Leave",
    startDate: "2026-08-05",
    endDate: "2026-08-07",
    numberOfDays: 3,
    reason: "Mild migraine headache without consultation documentation",
    applicationDate: "2026-08-08",
    doctorName: "Self / Local Chemist",
    consultationDate: "2026-08-05",
    treatmentDetails: "Over the counter analgesics",
    medicalCertificateName: "prescription.jpg",
    medicalCertificateUrl: sampleCertDataUri,
    medicalCertificateSize: "95 KB",
    declarationAccepted: true,
    status: "Rejected",
    adminRemarks: "Medical leave cannot be granted without registered MBBS practitioner certificate as per university guidelines.",
    reviewedBy: "Dr. Meenakshi Sundaram (Head of Department)",
    reviewedAt: "2026-08-09T12:00:00.000Z",
    submittedAt: "2026-08-08T10:00:00.000Z",
    createdAt: "2026-08-08T10:00:00.000Z",
    updatedAt: "2026-08-09T12:00:00.000Z",
    timeline: [
      {
        id: "t-1",
        status: "Submitted",
        title: "Application Submitted",
        description: "Application submitted.",
        timestamp: "2026-08-08T10:00:00.000Z",
        actor: "Rahul Verma (Student)",
      },
      {
        id: "t-2",
        status: "Rejected",
        title: "Application Rejected",
        description: "Medical leave cannot be granted without registered MBBS practitioner certificate as per university guidelines.",
        timestamp: "2026-08-09T12:00:00.000Z",
        actor: "Dr. Meenakshi Sundaram (Head of Department)",
        remarks: "Medical leave cannot be granted without registered MBBS practitioner certificate.",
      },
    ],
  },
];
